[package]
name = "circuit-benchmarks"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_proofs = { git = "https://github.com/taikoxyz/halo2.git", branch = "taiko/unstable" }
snark-verifier = { git = "https://github.com/taikoxyz/snark-verifier.git", branch = "a6-integration", default-features = false, features = [
    "loader_halo2",
    "system_halo2",
    "loader_evm",
    "parallel",
] }
snark-verifier-sdk = { git = "https://github.com/taikoxyz/snark-verifier.git", branch = "a6-integration", default-features = false, features = [
    "loader_halo2",
    "loader_evm",
    "parallel",
    "display",
    "halo2_circuit_params",
] }

ark-std = { version = "0.3", features = ["print-trace"] }
zkevm-circuits = { path = "../zkevm-circuits", features = ["test"] }
keccak256 = { path = "../keccak256" }
bus-mapping = { path = "../bus-mapping", features = ["test"] }
rand_xorshift = "0.3"
rand = "0.8"
itertools = "0.10"
eth-types = { path = "../eth-types" }
env_logger = "0.9"
ethers-signers = "=2.0.0"
mock = { path = "../mock" }
rand_chacha = "0.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "*"
hex = "0.4.3"

[features]
default = ["benches"]
benches = []
