[package]
name = "bus-mapping"
version = "0.1.0"
edition = "2021"
authors = ["CPerezz <c.perezbaro@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
eth-types = { path = "../eth-types" }
gadgets = { path = "../gadgets" }
keccak256 = { path = "../keccak256" }
mock = { path = "../mock", optional = true }

sha3 = "0.10"
once_cell = "1.17.1"
alloy-primitives = { version = "0.4", default-features = false, features = [
    "rlp",
    "serde",
    "std",
] }
alloy-sol-types = { version = "0.4" }
alloy-dyn-abi = { version = "0.4" }

ethers-core = "=2.0.0"
ethers-providers = "=2.0.0"
halo2_proofs = { git = "https://github.com/taikoxyz/halo2.git", branch = "taiko/unstable" }
itertools = "0.10"
lazy_static = "1.4"
log = "0.4.14"
rand = { version = "0.8" }
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.66"
strum = "0.24"
strum_macros = "0.24"

revm-precompile = "2.0.2"

[dev-dependencies]
hex = "0.4.3"
pretty_assertions = "1.0.0"
tokio = { version = "1.13", features = ["macros"] }
url = "2.2.2"
mock = { path = "../mock" }
rand = "0.8"

[features]
test = ["mock"]
disable_l2_trace_block = []
